//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDues
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_diferencias
    {
        public int idDetalle_Diferencias { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Codebars { get; set; }
        public decimal Contado { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Diferencia { get; set; }
        public int DiferenciasId { get; set; }
    
        public virtual diferencias diferencias { get; set; }
    }
}
