//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDues
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class duesEntities : DbContext
    {
        public duesEntities()
            : base(GetConnectionString())
        {
            this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    	public static string GetConnectionString()
        {
            //Obtiene el nombre usuario desde el token de la conexion
            string user ="root";
    
            //Obtiene el password a la bd 
            string password = System.Diagnostics.Debugger.IsAttached == true ? "" : "admindues";
    
            //Obtiene la bd de la empresa del token empresa
            string bd = System.Diagnostics.Debugger.IsAttached == true ? "dues" : "DuesInventarios";
    
            string servidor = System.Diagnostics.Debugger.IsAttached == true ? "localhost" : "192.168.1.20";
    
            string connString = "metadata=res://*/Empresa.csdl|res://*/Empresa.ssdl|res://*/Empresa.msl;provider=MySql.Data.MySqlClient;provider connection string=\"server={3};user id={0};password={1};persistsecurityinfo=True;database={2}\"";
            return String.Format(connString, user, password, bd, servidor);
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<colonias> colonias { get; set; }
        public virtual DbSet<detalle_inventario> detalle_inventario { get; set; }
        public virtual DbSet<detalle_inventario_aplicado> detalle_inventario_aplicado { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<inventario_aplicado> inventario_aplicado { get; set; }
        public virtual DbSet<tokens> tokens { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
