//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDues
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPLN
    {
        public short ListNum { get; set; }
        public string ListName { get; set; }
        public Nullable<short> BASE_NUM { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<short> RoundSys { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string DataSource { get; set; }
        public Nullable<int> SPPCounter { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string IsGrossPrc { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ValidFor { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PrimCurr { get; set; }
        public string AddCurr1 { get; set; }
        public string AddCurr2 { get; set; }
        public string RoundRule { get; set; }
        public Nullable<decimal> ExtAmount { get; set; }
        public string RndFrmtInt { get; set; }
        public string RndFrmtDec { get; set; }
    }
}
